package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.BoOrderCost;
import com.borrow.manage.model.dto.BoOrderCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoOrderCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int countByExample(BoOrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int deleteByExample(BoOrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int insert(BoOrderCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int insertSelective(BoOrderCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    List<BoOrderCost> selectByExample(BoOrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    BoOrderCost selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BoOrderCost record, @Param("example") BoOrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BoOrderCost record, @Param("example") BoOrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoOrderCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_order_cost
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BoOrderCost record);
}