package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.BoOverdueReduceRecord;
import com.borrow.manage.model.dto.BoOverdueReduceRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoOverdueReduceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int countByExample(BoOverdueReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int deleteByExample(BoOverdueReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int insert(BoOverdueReduceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int insertSelective(BoOverdueReduceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    List<BoOverdueReduceRecord> selectByExample(BoOverdueReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    BoOverdueReduceRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BoOverdueReduceRecord record, @Param("example") BoOverdueReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BoOverdueReduceRecord record, @Param("example") BoOverdueReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoOverdueReduceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BoOverdueReduceRecord record);
}