package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.BoOverduerReduceRecord;
import com.borrow.manage.model.dto.BoOverduerReduceRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoOverduerReduceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int countByExample(BoOverduerReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int deleteByExample(BoOverduerReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int insert(BoOverduerReduceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int insertSelective(BoOverduerReduceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    List<BoOverduerReduceRecord> selectByExample(BoOverduerReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    BoOverduerReduceRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BoOverduerReduceRecord record, @Param("example") BoOverduerReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BoOverduerReduceRecord record, @Param("example") BoOverduerReduceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoOverduerReduceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_overdue_reduce_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BoOverduerReduceRecord record);
}