package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.BorrowRepayment;
import com.borrow.manage.model.dto.BorrowRepaymentExample;
import java.util.List;

import com.borrow.manage.vo.OrderRepayListReq;
import com.borrow.manage.vo.OrderRepayListRes;
import org.apache.ibatis.annotations.Param;

public interface BorrowRepaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int countByExample(BorrowRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int deleteByExample(BorrowRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int insert(BorrowRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int insertSelective(BorrowRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    List<BorrowRepayment> selectByExample(BorrowRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    BorrowRepayment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BorrowRepayment record, @Param("example") BorrowRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BorrowRepayment record, @Param("example") BorrowRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BorrowRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BorrowRepayment record);

    /**
     * 还款明细查询
     * @param orderRepayListReq
     * @return
     */
    List<OrderRepayListRes> selOrderRepayList(OrderRepayListReq orderRepayListReq);

}