package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.BorrowSalesman;
import com.borrow.manage.model.dto.BorrowSalesmanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowSalesmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int countByExample(BorrowSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int deleteByExample(BorrowSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int insert(BorrowSalesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int insertSelective(BorrowSalesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    List<BorrowSalesman> selectByExample(BorrowSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    BorrowSalesman selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BorrowSalesman record, @Param("example") BorrowSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BorrowSalesman record, @Param("example") BorrowSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BorrowSalesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_salesman
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BorrowSalesman record);
}