package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.BorrowProduct;
import com.borrow.manage.model.dto.BorrowProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int countByExample(BorrowProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int deleteByExample(BorrowProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int insert(BorrowProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int insertSelective(BorrowProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    List<BorrowProduct> selectByExample(BorrowProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    BorrowProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BorrowProduct record, @Param("example") BorrowProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BorrowProduct record, @Param("example") BorrowProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BorrowProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BorrowProduct record);
}