package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.BorrowOrder;
import com.borrow.manage.model.dto.BorrowOrderExample;
import java.util.List;

import com.borrow.manage.vo.OrderListReq;
import com.borrow.manage.vo.OrderListRes;
import com.borrow.manage.vo.OrderPayListReq;
import com.borrow.manage.vo.OrderPayListRes;
import org.apache.ibatis.annotations.Param;

public interface BorrowOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int countByExample(BorrowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int deleteByExample(BorrowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int insert(BorrowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int insertSelective(BorrowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    List<BorrowOrder> selectByExample(BorrowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    BorrowOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BorrowOrder record, @Param("example") BorrowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BorrowOrder record, @Param("example") BorrowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BorrowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BorrowOrder record);


    /**
     * 订单列表查询
     * @param orderListReq
     * @return
     */
    List<OrderListRes>  selOrderList(OrderListReq orderListReq);

    /**
     * 订单还款列表查询
     * @param orderPayListReq
     * @return
     */
    List<OrderPayListRes>  selOrderPayList(OrderPayListReq orderPayListReq);

    /**
     * 更新订单还款期数
     * @param orderId
     * @return
     */
    int updateBoPayExpectCount(Long orderId);
}
