package com.borrow.manage.dao.mapper;

import com.borrow.manage.model.dto.UserCar;
import com.borrow.manage.model.dto.UserCarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int countByExample(UserCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int deleteByExample(UserCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int insert(UserCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int insertSelective(UserCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    List<UserCar> selectByExample(UserCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    UserCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserCar record, @Param("example") UserCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserCar record, @Param("example") UserCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserCar record);
}