package com.borrow.manage.model.dto;

import java.util.Date;

public class BoOrderAudit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.auth_name
     *
     * @mbggenerated
     */
    private String authName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.audit_key
     *
     * @mbggenerated
     */
    private String auditKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.audit_value
     *
     * @mbggenerated
     */
    private String auditValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.audit_state
     *
     * @mbggenerated
     */
    private Integer auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_order_audit.audit_file_url
     *
     * @mbggenerated
     */
    private String auditFileUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.id
     *
     * @return the value of bo_order_audit.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.id
     *
     * @param id the value for bo_order_audit.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.disabled
     *
     * @return the value of bo_order_audit.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.disabled
     *
     * @param disabled the value for bo_order_audit.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.uuid
     *
     * @return the value of bo_order_audit.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.uuid
     *
     * @param uuid the value for bo_order_audit.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.create_user
     *
     * @return the value of bo_order_audit.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.create_user
     *
     * @param createUser the value for bo_order_audit.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.create_time
     *
     * @return the value of bo_order_audit.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.create_time
     *
     * @param createTime the value for bo_order_audit.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.update_user
     *
     * @return the value of bo_order_audit.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.update_user
     *
     * @param updateUser the value for bo_order_audit.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.update_time
     *
     * @return the value of bo_order_audit.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.update_time
     *
     * @param updateTime the value for bo_order_audit.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.remark
     *
     * @return the value of bo_order_audit.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.remark
     *
     * @param remark the value for bo_order_audit.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.order_id
     *
     * @return the value of bo_order_audit.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.order_id
     *
     * @param orderId the value for bo_order_audit.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.auth_name
     *
     * @return the value of bo_order_audit.auth_name
     *
     * @mbggenerated
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.auth_name
     *
     * @param authName the value for bo_order_audit.auth_name
     *
     * @mbggenerated
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.audit_key
     *
     * @return the value of bo_order_audit.audit_key
     *
     * @mbggenerated
     */
    public String getAuditKey() {
        return auditKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.audit_key
     *
     * @param auditKey the value for bo_order_audit.audit_key
     *
     * @mbggenerated
     */
    public void setAuditKey(String auditKey) {
        this.auditKey = auditKey == null ? null : auditKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.audit_value
     *
     * @return the value of bo_order_audit.audit_value
     *
     * @mbggenerated
     */
    public String getAuditValue() {
        return auditValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.audit_value
     *
     * @param auditValue the value for bo_order_audit.audit_value
     *
     * @mbggenerated
     */
    public void setAuditValue(String auditValue) {
        this.auditValue = auditValue == null ? null : auditValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.audit_state
     *
     * @return the value of bo_order_audit.audit_state
     *
     * @mbggenerated
     */
    public Integer getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.audit_state
     *
     * @param auditState the value for bo_order_audit.audit_state
     *
     * @mbggenerated
     */
    public void setAuditState(Integer auditState) {
        this.auditState = auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.audit_time
     *
     * @return the value of bo_order_audit.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.audit_time
     *
     * @param auditTime the value for bo_order_audit.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_order_audit.audit_file_url
     *
     * @return the value of bo_order_audit.audit_file_url
     *
     * @mbggenerated
     */
    public String getAuditFileUrl() {
        return auditFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_order_audit.audit_file_url
     *
     * @param auditFileUrl the value for bo_order_audit.audit_file_url
     *
     * @mbggenerated
     */
    public void setAuditFileUrl(String auditFileUrl) {
        this.auditFileUrl = auditFileUrl == null ? null : auditFileUrl.trim();
    }
}
