package com.borrow.manage.model.dto;

import java.util.Date;

public class BoProductRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.p_uid
     *
     * @mbggenerated
     */
    private String pUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.rate_key
     *
     * @mbggenerated
     */
    private String rateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.rate_value
     *
     * @mbggenerated
     */
    private String rateValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_product_rate.rate_desc
     *
     * @mbggenerated
     */
    private String rateDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.id
     *
     * @return the value of bo_product_rate.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.id
     *
     * @param id the value for bo_product_rate.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.disabled
     *
     * @return the value of bo_product_rate.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.disabled
     *
     * @param disabled the value for bo_product_rate.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.uuid
     *
     * @return the value of bo_product_rate.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.uuid
     *
     * @param uuid the value for bo_product_rate.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.create_user
     *
     * @return the value of bo_product_rate.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.create_user
     *
     * @param createUser the value for bo_product_rate.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.create_time
     *
     * @return the value of bo_product_rate.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.create_time
     *
     * @param createTime the value for bo_product_rate.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.update_user
     *
     * @return the value of bo_product_rate.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.update_user
     *
     * @param updateUser the value for bo_product_rate.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.update_time
     *
     * @return the value of bo_product_rate.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.update_time
     *
     * @param updateTime the value for bo_product_rate.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.remark
     *
     * @return the value of bo_product_rate.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.remark
     *
     * @param remark the value for bo_product_rate.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.p_uid
     *
     * @return the value of bo_product_rate.p_uid
     *
     * @mbggenerated
     */
    public String getpUid() {
        return pUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.p_uid
     *
     * @param pUid the value for bo_product_rate.p_uid
     *
     * @mbggenerated
     */
    public void setpUid(String pUid) {
        this.pUid = pUid == null ? null : pUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.p_code
     *
     * @return the value of bo_product_rate.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.p_code
     *
     * @param pCode the value for bo_product_rate.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.rate_key
     *
     * @return the value of bo_product_rate.rate_key
     *
     * @mbggenerated
     */
    public String getRateKey() {
        return rateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.rate_key
     *
     * @param rateKey the value for bo_product_rate.rate_key
     *
     * @mbggenerated
     */
    public void setRateKey(String rateKey) {
        this.rateKey = rateKey == null ? null : rateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.rate_value
     *
     * @return the value of bo_product_rate.rate_value
     *
     * @mbggenerated
     */
    public String getRateValue() {
        return rateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.rate_value
     *
     * @param rateValue the value for bo_product_rate.rate_value
     *
     * @mbggenerated
     */
    public void setRateValue(String rateValue) {
        this.rateValue = rateValue == null ? null : rateValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_product_rate.rate_desc
     *
     * @return the value of bo_product_rate.rate_desc
     *
     * @mbggenerated
     */
    public String getRateDesc() {
        return rateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_product_rate.rate_desc
     *
     * @param rateDesc the value for bo_product_rate.rate_desc
     *
     * @mbggenerated
     */
    public void setRateDesc(String rateDesc) {
        this.rateDesc = rateDesc == null ? null : rateDesc.trim();
    }
}