package com.borrow.manage.model.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BorrowRepaymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public BorrowRepaymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNull() {
            addCriterion("disabled is null");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNotNull() {
            addCriterion("disabled is not null");
            return (Criteria) this;
        }

        public Criteria andDisabledEqualTo(Boolean value) {
            addCriterion("disabled =", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotEqualTo(Boolean value) {
            addCriterion("disabled <>", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThan(Boolean value) {
            addCriterion("disabled >", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("disabled >=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThan(Boolean value) {
            addCriterion("disabled <", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThanOrEqualTo(Boolean value) {
            addCriterion("disabled <=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledIn(List<Boolean> values) {
            addCriterion("disabled in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotIn(List<Boolean> values) {
            addCriterion("disabled not in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledBetween(Boolean value1, Boolean value2) {
            addCriterion("disabled between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("disabled not between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRepayIdIsNull() {
            addCriterion("repay_id is null");
            return (Criteria) this;
        }

        public Criteria andRepayIdIsNotNull() {
            addCriterion("repay_id is not null");
            return (Criteria) this;
        }

        public Criteria andRepayIdEqualTo(Long value) {
            addCriterion("repay_id =", value, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdNotEqualTo(Long value) {
            addCriterion("repay_id <>", value, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdGreaterThan(Long value) {
            addCriterion("repay_id >", value, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdGreaterThanOrEqualTo(Long value) {
            addCriterion("repay_id >=", value, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdLessThan(Long value) {
            addCriterion("repay_id <", value, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdLessThanOrEqualTo(Long value) {
            addCriterion("repay_id <=", value, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdIn(List<Long> values) {
            addCriterion("repay_id in", values, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdNotIn(List<Long> values) {
            addCriterion("repay_id not in", values, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdBetween(Long value1, Long value2) {
            addCriterion("repay_id between", value1, value2, "repayId");
            return (Criteria) this;
        }

        public Criteria andRepayIdNotBetween(Long value1, Long value2) {
            addCriterion("repay_id not between", value1, value2, "repayId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNull() {
            addCriterion("user_uid is null");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNotNull() {
            addCriterion("user_uid is not null");
            return (Criteria) this;
        }

        public Criteria andUserUidEqualTo(String value) {
            addCriterion("user_uid =", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotEqualTo(String value) {
            addCriterion("user_uid <>", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThan(String value) {
            addCriterion("user_uid >", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThanOrEqualTo(String value) {
            addCriterion("user_uid >=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThan(String value) {
            addCriterion("user_uid <", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThanOrEqualTo(String value) {
            addCriterion("user_uid <=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLike(String value) {
            addCriterion("user_uid like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotLike(String value) {
            addCriterion("user_uid not like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIn(List<String> values) {
            addCriterion("user_uid in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotIn(List<String> values) {
            addCriterion("user_uid not in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidBetween(String value1, String value2) {
            addCriterion("user_uid between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotBetween(String value1, String value2) {
            addCriterion("user_uid not between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andRepayAmountIsNull() {
            addCriterion("repay_amount is null");
            return (Criteria) this;
        }

        public Criteria andRepayAmountIsNotNull() {
            addCriterion("repay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRepayAmountEqualTo(BigDecimal value) {
            addCriterion("repay_amount =", value, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountNotEqualTo(BigDecimal value) {
            addCriterion("repay_amount <>", value, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountGreaterThan(BigDecimal value) {
            addCriterion("repay_amount >", value, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_amount >=", value, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountLessThan(BigDecimal value) {
            addCriterion("repay_amount <", value, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_amount <=", value, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountIn(List<BigDecimal> values) {
            addCriterion("repay_amount in", values, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountNotIn(List<BigDecimal> values) {
            addCriterion("repay_amount not in", values, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_amount between", value1, value2, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andRepayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_amount not between", value1, value2, "repayAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountIsNull() {
            addCriterion("capital_amount is null");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountIsNotNull() {
            addCriterion("capital_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountEqualTo(BigDecimal value) {
            addCriterion("capital_amount =", value, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountNotEqualTo(BigDecimal value) {
            addCriterion("capital_amount <>", value, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountGreaterThan(BigDecimal value) {
            addCriterion("capital_amount >", value, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("capital_amount >=", value, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountLessThan(BigDecimal value) {
            addCriterion("capital_amount <", value, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("capital_amount <=", value, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountIn(List<BigDecimal> values) {
            addCriterion("capital_amount in", values, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountNotIn(List<BigDecimal> values) {
            addCriterion("capital_amount not in", values, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("capital_amount between", value1, value2, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andCapitalAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("capital_amount not between", value1, value2, "capitalAmount");
            return (Criteria) this;
        }

        public Criteria andBrTimeIsNull() {
            addCriterion("br_time is null");
            return (Criteria) this;
        }

        public Criteria andBrTimeIsNotNull() {
            addCriterion("br_time is not null");
            return (Criteria) this;
        }

        public Criteria andBrTimeEqualTo(Date value) {
            addCriterionForJDBCDate("br_time =", value, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("br_time <>", value, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("br_time >", value, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("br_time >=", value, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeLessThan(Date value) {
            addCriterionForJDBCDate("br_time <", value, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("br_time <=", value, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeIn(List<Date> values) {
            addCriterionForJDBCDate("br_time in", values, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("br_time not in", values, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("br_time between", value1, value2, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("br_time not between", value1, value2, "brTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeIsNull() {
            addCriterion("br_repay_time is null");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeIsNotNull() {
            addCriterion("br_repay_time is not null");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeEqualTo(Date value) {
            addCriterion("br_repay_time =", value, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeNotEqualTo(Date value) {
            addCriterion("br_repay_time <>", value, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeGreaterThan(Date value) {
            addCriterion("br_repay_time >", value, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("br_repay_time >=", value, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeLessThan(Date value) {
            addCriterion("br_repay_time <", value, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeLessThanOrEqualTo(Date value) {
            addCriterion("br_repay_time <=", value, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeIn(List<Date> values) {
            addCriterion("br_repay_time in", values, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeNotIn(List<Date> values) {
            addCriterion("br_repay_time not in", values, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeBetween(Date value1, Date value2) {
            addCriterion("br_repay_time between", value1, value2, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andBrRepayTimeNotBetween(Date value1, Date value2) {
            addCriterion("br_repay_time not between", value1, value2, "brRepayTime");
            return (Criteria) this;
        }

        public Criteria andRepayExpectIsNull() {
            addCriterion("repay_expect is null");
            return (Criteria) this;
        }

        public Criteria andRepayExpectIsNotNull() {
            addCriterion("repay_expect is not null");
            return (Criteria) this;
        }

        public Criteria andRepayExpectEqualTo(Integer value) {
            addCriterion("repay_expect =", value, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectNotEqualTo(Integer value) {
            addCriterion("repay_expect <>", value, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectGreaterThan(Integer value) {
            addCriterion("repay_expect >", value, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectGreaterThanOrEqualTo(Integer value) {
            addCriterion("repay_expect >=", value, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectLessThan(Integer value) {
            addCriterion("repay_expect <", value, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectLessThanOrEqualTo(Integer value) {
            addCriterion("repay_expect <=", value, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectIn(List<Integer> values) {
            addCriterion("repay_expect in", values, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectNotIn(List<Integer> values) {
            addCriterion("repay_expect not in", values, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectBetween(Integer value1, Integer value2) {
            addCriterion("repay_expect between", value1, value2, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andRepayExpectNotBetween(Integer value1, Integer value2) {
            addCriterion("repay_expect not between", value1, value2, "repayExpect");
            return (Criteria) this;
        }

        public Criteria andInterestAmountIsNull() {
            addCriterion("interest_amount is null");
            return (Criteria) this;
        }

        public Criteria andInterestAmountIsNotNull() {
            addCriterion("interest_amount is not null");
            return (Criteria) this;
        }

        public Criteria andInterestAmountEqualTo(BigDecimal value) {
            addCriterion("interest_amount =", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountNotEqualTo(BigDecimal value) {
            addCriterion("interest_amount <>", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountGreaterThan(BigDecimal value) {
            addCriterion("interest_amount >", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("interest_amount >=", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountLessThan(BigDecimal value) {
            addCriterion("interest_amount <", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("interest_amount <=", value, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountIn(List<BigDecimal> values) {
            addCriterion("interest_amount in", values, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountNotIn(List<BigDecimal> values) {
            addCriterion("interest_amount not in", values, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest_amount between", value1, value2, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andInterestAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest_amount not between", value1, value2, "interestAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountIsNull() {
            addCriterion("punish_amount is null");
            return (Criteria) this;
        }

        public Criteria andPunishAmountIsNotNull() {
            addCriterion("punish_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPunishAmountEqualTo(BigDecimal value) {
            addCriterion("punish_amount =", value, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountNotEqualTo(BigDecimal value) {
            addCriterion("punish_amount <>", value, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountGreaterThan(BigDecimal value) {
            addCriterion("punish_amount >", value, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("punish_amount >=", value, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountLessThan(BigDecimal value) {
            addCriterion("punish_amount <", value, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("punish_amount <=", value, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountIn(List<BigDecimal> values) {
            addCriterion("punish_amount in", values, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountNotIn(List<BigDecimal> values) {
            addCriterion("punish_amount not in", values, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("punish_amount between", value1, value2, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andPunishAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("punish_amount not between", value1, value2, "punishAmount");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNull() {
            addCriterion("service_fee is null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNotNull() {
            addCriterion("service_fee is not null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeEqualTo(BigDecimal value) {
            addCriterion("service_fee =", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotEqualTo(BigDecimal value) {
            addCriterion("service_fee <>", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThan(BigDecimal value) {
            addCriterion("service_fee >", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("service_fee >=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThan(BigDecimal value) {
            addCriterion("service_fee <", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("service_fee <=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIn(List<BigDecimal> values) {
            addCriterion("service_fee in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotIn(List<BigDecimal> values) {
            addCriterion("service_fee not in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("service_fee between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("service_fee not between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeIsNull() {
            addCriterion("early_pay_fee is null");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeIsNotNull() {
            addCriterion("early_pay_fee is not null");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeEqualTo(BigDecimal value) {
            addCriterion("early_pay_fee =", value, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeNotEqualTo(BigDecimal value) {
            addCriterion("early_pay_fee <>", value, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeGreaterThan(BigDecimal value) {
            addCriterion("early_pay_fee >", value, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("early_pay_fee >=", value, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeLessThan(BigDecimal value) {
            addCriterion("early_pay_fee <", value, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("early_pay_fee <=", value, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeIn(List<BigDecimal> values) {
            addCriterion("early_pay_fee in", values, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeNotIn(List<BigDecimal> values) {
            addCriterion("early_pay_fee not in", values, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("early_pay_fee between", value1, value2, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andEarlyPayFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("early_pay_fee not between", value1, value2, "earlyPayFee");
            return (Criteria) this;
        }

        public Criteria andRepayStatusIsNull() {
            addCriterion("repay_status is null");
            return (Criteria) this;
        }

        public Criteria andRepayStatusIsNotNull() {
            addCriterion("repay_status is not null");
            return (Criteria) this;
        }

        public Criteria andRepayStatusEqualTo(Integer value) {
            addCriterion("repay_status =", value, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusNotEqualTo(Integer value) {
            addCriterion("repay_status <>", value, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusGreaterThan(Integer value) {
            addCriterion("repay_status >", value, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("repay_status >=", value, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusLessThan(Integer value) {
            addCriterion("repay_status <", value, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusLessThanOrEqualTo(Integer value) {
            addCriterion("repay_status <=", value, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusIn(List<Integer> values) {
            addCriterion("repay_status in", values, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusNotIn(List<Integer> values) {
            addCriterion("repay_status not in", values, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusBetween(Integer value1, Integer value2) {
            addCriterion("repay_status between", value1, value2, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("repay_status not between", value1, value2, "repayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusIsNull() {
            addCriterion("bo_repay_status is null");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusIsNotNull() {
            addCriterion("bo_repay_status is not null");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusEqualTo(Integer value) {
            addCriterion("bo_repay_status =", value, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusNotEqualTo(Integer value) {
            addCriterion("bo_repay_status <>", value, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusGreaterThan(Integer value) {
            addCriterion("bo_repay_status >", value, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_repay_status >=", value, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusLessThan(Integer value) {
            addCriterion("bo_repay_status <", value, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusLessThanOrEqualTo(Integer value) {
            addCriterion("bo_repay_status <=", value, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusIn(List<Integer> values) {
            addCriterion("bo_repay_status in", values, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusNotIn(List<Integer> values) {
            addCriterion("bo_repay_status not in", values, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusBetween(Integer value1, Integer value2) {
            addCriterion("bo_repay_status between", value1, value2, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andBoRepayStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_repay_status not between", value1, value2, "boRepayStatus");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIsNull() {
            addCriterion("repay_type is null");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIsNotNull() {
            addCriterion("repay_type is not null");
            return (Criteria) this;
        }

        public Criteria andRepayTypeEqualTo(Integer value) {
            addCriterion("repay_type =", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotEqualTo(Integer value) {
            addCriterion("repay_type <>", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeGreaterThan(Integer value) {
            addCriterion("repay_type >", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("repay_type >=", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLessThan(Integer value) {
            addCriterion("repay_type <", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("repay_type <=", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIn(List<Integer> values) {
            addCriterion("repay_type in", values, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotIn(List<Integer> values) {
            addCriterion("repay_type not in", values, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeBetween(Integer value1, Integer value2) {
            addCriterion("repay_type between", value1, value2, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("repay_type not between", value1, value2, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountIsNull() {
            addCriterion("repay_finish_amount is null");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountIsNotNull() {
            addCriterion("repay_finish_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountEqualTo(BigDecimal value) {
            addCriterion("repay_finish_amount =", value, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountNotEqualTo(BigDecimal value) {
            addCriterion("repay_finish_amount <>", value, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountGreaterThan(BigDecimal value) {
            addCriterion("repay_finish_amount >", value, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_finish_amount >=", value, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountLessThan(BigDecimal value) {
            addCriterion("repay_finish_amount <", value, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_finish_amount <=", value, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountIn(List<BigDecimal> values) {
            addCriterion("repay_finish_amount in", values, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountNotIn(List<BigDecimal> values) {
            addCriterion("repay_finish_amount not in", values, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_finish_amount between", value1, value2, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andRepayFinishAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_finish_amount not between", value1, value2, "repayFinishAmount");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusIsNull() {
            addCriterion("surety_status is null");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusIsNotNull() {
            addCriterion("surety_status is not null");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusEqualTo(Integer value) {
            addCriterion("surety_status =", value, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusNotEqualTo(Integer value) {
            addCriterion("surety_status <>", value, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusGreaterThan(Integer value) {
            addCriterion("surety_status >", value, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("surety_status >=", value, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusLessThan(Integer value) {
            addCriterion("surety_status <", value, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("surety_status <=", value, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusIn(List<Integer> values) {
            addCriterion("surety_status in", values, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusNotIn(List<Integer> values) {
            addCriterion("surety_status not in", values, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusBetween(Integer value1, Integer value2) {
            addCriterion("surety_status between", value1, value2, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("surety_status not between", value1, value2, "suretyStatus");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeIsNull() {
            addCriterion("surety_time is null");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeIsNotNull() {
            addCriterion("surety_time is not null");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeEqualTo(Date value) {
            addCriterion("surety_time =", value, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeNotEqualTo(Date value) {
            addCriterion("surety_time <>", value, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeGreaterThan(Date value) {
            addCriterion("surety_time >", value, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("surety_time >=", value, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeLessThan(Date value) {
            addCriterion("surety_time <", value, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeLessThanOrEqualTo(Date value) {
            addCriterion("surety_time <=", value, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeIn(List<Date> values) {
            addCriterion("surety_time in", values, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeNotIn(List<Date> values) {
            addCriterion("surety_time not in", values, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeBetween(Date value1, Date value2) {
            addCriterion("surety_time between", value1, value2, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andSuretyTimeNotBetween(Date value1, Date value2) {
            addCriterion("surety_time not between", value1, value2, "suretyTime");
            return (Criteria) this;
        }

        public Criteria andFineAmountIsNull() {
            addCriterion("fine_amount is null");
            return (Criteria) this;
        }

        public Criteria andFineAmountIsNotNull() {
            addCriterion("fine_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFineAmountEqualTo(BigDecimal value) {
            addCriterion("fine_amount =", value, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountNotEqualTo(BigDecimal value) {
            addCriterion("fine_amount <>", value, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountGreaterThan(BigDecimal value) {
            addCriterion("fine_amount >", value, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fine_amount >=", value, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountLessThan(BigDecimal value) {
            addCriterion("fine_amount <", value, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fine_amount <=", value, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountIn(List<BigDecimal> values) {
            addCriterion("fine_amount in", values, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountNotIn(List<BigDecimal> values) {
            addCriterion("fine_amount not in", values, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fine_amount between", value1, value2, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andFineAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fine_amount not between", value1, value2, "fineAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountIsNull() {
            addCriterion("reduce_punish_amount is null");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountIsNotNull() {
            addCriterion("reduce_punish_amount is not null");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountEqualTo(BigDecimal value) {
            addCriterion("reduce_punish_amount =", value, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountNotEqualTo(BigDecimal value) {
            addCriterion("reduce_punish_amount <>", value, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountGreaterThan(BigDecimal value) {
            addCriterion("reduce_punish_amount >", value, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reduce_punish_amount >=", value, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountLessThan(BigDecimal value) {
            addCriterion("reduce_punish_amount <", value, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reduce_punish_amount <=", value, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountIn(List<BigDecimal> values) {
            addCriterion("reduce_punish_amount in", values, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountNotIn(List<BigDecimal> values) {
            addCriterion("reduce_punish_amount not in", values, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduce_punish_amount between", value1, value2, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReducePunishAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduce_punish_amount not between", value1, value2, "reducePunishAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountIsNull() {
            addCriterion("reduce_fine_amount is null");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountIsNotNull() {
            addCriterion("reduce_fine_amount is not null");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountEqualTo(BigDecimal value) {
            addCriterion("reduce_fine_amount =", value, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountNotEqualTo(BigDecimal value) {
            addCriterion("reduce_fine_amount <>", value, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountGreaterThan(BigDecimal value) {
            addCriterion("reduce_fine_amount >", value, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reduce_fine_amount >=", value, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountLessThan(BigDecimal value) {
            addCriterion("reduce_fine_amount <", value, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reduce_fine_amount <=", value, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountIn(List<BigDecimal> values) {
            addCriterion("reduce_fine_amount in", values, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountNotIn(List<BigDecimal> values) {
            addCriterion("reduce_fine_amount not in", values, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduce_fine_amount between", value1, value2, "reduceFineAmount");
            return (Criteria) this;
        }

        public Criteria andReduceFineAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduce_fine_amount not between", value1, value2, "reduceFineAmount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_repayment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_repayment
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
