package com.borrow.manage.model.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BorrowOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public BorrowOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNull() {
            addCriterion("disabled is null");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNotNull() {
            addCriterion("disabled is not null");
            return (Criteria) this;
        }

        public Criteria andDisabledEqualTo(Boolean value) {
            addCriterion("disabled =", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotEqualTo(Boolean value) {
            addCriterion("disabled <>", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThan(Boolean value) {
            addCriterion("disabled >", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("disabled >=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThan(Boolean value) {
            addCriterion("disabled <", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThanOrEqualTo(Boolean value) {
            addCriterion("disabled <=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledIn(List<Boolean> values) {
            addCriterion("disabled in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotIn(List<Boolean> values) {
            addCriterion("disabled not in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledBetween(Boolean value1, Boolean value2) {
            addCriterion("disabled between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("disabled not between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andBuesTypeIsNull() {
            addCriterion("bues_type is null");
            return (Criteria) this;
        }

        public Criteria andBuesTypeIsNotNull() {
            addCriterion("bues_type is not null");
            return (Criteria) this;
        }

        public Criteria andBuesTypeEqualTo(Integer value) {
            addCriterion("bues_type =", value, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeNotEqualTo(Integer value) {
            addCriterion("bues_type <>", value, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeGreaterThan(Integer value) {
            addCriterion("bues_type >", value, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bues_type >=", value, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeLessThan(Integer value) {
            addCriterion("bues_type <", value, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeLessThanOrEqualTo(Integer value) {
            addCriterion("bues_type <=", value, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeIn(List<Integer> values) {
            addCriterion("bues_type in", values, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeNotIn(List<Integer> values) {
            addCriterion("bues_type not in", values, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeBetween(Integer value1, Integer value2) {
            addCriterion("bues_type between", value1, value2, "buesType");
            return (Criteria) this;
        }

        public Criteria andBuesTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("bues_type not between", value1, value2, "buesType");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNull() {
            addCriterion("user_uid is null");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNotNull() {
            addCriterion("user_uid is not null");
            return (Criteria) this;
        }

        public Criteria andUserUidEqualTo(String value) {
            addCriterion("user_uid =", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotEqualTo(String value) {
            addCriterion("user_uid <>", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThan(String value) {
            addCriterion("user_uid >", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThanOrEqualTo(String value) {
            addCriterion("user_uid >=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThan(String value) {
            addCriterion("user_uid <", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThanOrEqualTo(String value) {
            addCriterion("user_uid <=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLike(String value) {
            addCriterion("user_uid like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotLike(String value) {
            addCriterion("user_uid not like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIn(List<String> values) {
            addCriterion("user_uid in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotIn(List<String> values) {
            addCriterion("user_uid not in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidBetween(String value1, String value2) {
            addCriterion("user_uid between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotBetween(String value1, String value2) {
            addCriterion("user_uid not between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andProductUidIsNull() {
            addCriterion("product_uid is null");
            return (Criteria) this;
        }

        public Criteria andProductUidIsNotNull() {
            addCriterion("product_uid is not null");
            return (Criteria) this;
        }

        public Criteria andProductUidEqualTo(String value) {
            addCriterion("product_uid =", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidNotEqualTo(String value) {
            addCriterion("product_uid <>", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidGreaterThan(String value) {
            addCriterion("product_uid >", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidGreaterThanOrEqualTo(String value) {
            addCriterion("product_uid >=", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidLessThan(String value) {
            addCriterion("product_uid <", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidLessThanOrEqualTo(String value) {
            addCriterion("product_uid <=", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidLike(String value) {
            addCriterion("product_uid like", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidNotLike(String value) {
            addCriterion("product_uid not like", value, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidIn(List<String> values) {
            addCriterion("product_uid in", values, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidNotIn(List<String> values) {
            addCriterion("product_uid not in", values, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidBetween(String value1, String value2) {
            addCriterion("product_uid between", value1, value2, "productUid");
            return (Criteria) this;
        }

        public Criteria andProductUidNotBetween(String value1, String value2) {
            addCriterion("product_uid not between", value1, value2, "productUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidIsNull() {
            addCriterion("b_car_uid is null");
            return (Criteria) this;
        }

        public Criteria andBCarUidIsNotNull() {
            addCriterion("b_car_uid is not null");
            return (Criteria) this;
        }

        public Criteria andBCarUidEqualTo(String value) {
            addCriterion("b_car_uid =", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidNotEqualTo(String value) {
            addCriterion("b_car_uid <>", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidGreaterThan(String value) {
            addCriterion("b_car_uid >", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidGreaterThanOrEqualTo(String value) {
            addCriterion("b_car_uid >=", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidLessThan(String value) {
            addCriterion("b_car_uid <", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidLessThanOrEqualTo(String value) {
            addCriterion("b_car_uid <=", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidLike(String value) {
            addCriterion("b_car_uid like", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidNotLike(String value) {
            addCriterion("b_car_uid not like", value, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidIn(List<String> values) {
            addCriterion("b_car_uid in", values, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidNotIn(List<String> values) {
            addCriterion("b_car_uid not in", values, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidBetween(String value1, String value2) {
            addCriterion("b_car_uid between", value1, value2, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andBCarUidNotBetween(String value1, String value2) {
            addCriterion("b_car_uid not between", value1, value2, "bCarUid");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNull() {
            addCriterion("p_code is null");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNotNull() {
            addCriterion("p_code is not null");
            return (Criteria) this;
        }

        public Criteria andPCodeEqualTo(String value) {
            addCriterion("p_code =", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotEqualTo(String value) {
            addCriterion("p_code <>", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThan(String value) {
            addCriterion("p_code >", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThanOrEqualTo(String value) {
            addCriterion("p_code >=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThan(String value) {
            addCriterion("p_code <", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThanOrEqualTo(String value) {
            addCriterion("p_code <=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLike(String value) {
            addCriterion("p_code like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotLike(String value) {
            addCriterion("p_code not like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeIn(List<String> values) {
            addCriterion("p_code in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotIn(List<String> values) {
            addCriterion("p_code not in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeBetween(String value1, String value2) {
            addCriterion("p_code between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotBetween(String value1, String value2) {
            addCriterion("p_code not between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIsNull() {
            addCriterion("plate_number is null");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIsNotNull() {
            addCriterion("plate_number is not null");
            return (Criteria) this;
        }

        public Criteria andPlateNumberEqualTo(String value) {
            addCriterion("plate_number =", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotEqualTo(String value) {
            addCriterion("plate_number <>", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberGreaterThan(String value) {
            addCriterion("plate_number >", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberGreaterThanOrEqualTo(String value) {
            addCriterion("plate_number >=", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLessThan(String value) {
            addCriterion("plate_number <", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLessThanOrEqualTo(String value) {
            addCriterion("plate_number <=", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLike(String value) {
            addCriterion("plate_number like", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotLike(String value) {
            addCriterion("plate_number not like", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIn(List<String> values) {
            addCriterion("plate_number in", values, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotIn(List<String> values) {
            addCriterion("plate_number not in", values, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberBetween(String value1, String value2) {
            addCriterion("plate_number between", value1, value2, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotBetween(String value1, String value2) {
            addCriterion("plate_number not between", value1, value2, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidIsNull() {
            addCriterion("salesman_uid is null");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidIsNotNull() {
            addCriterion("salesman_uid is not null");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidEqualTo(String value) {
            addCriterion("salesman_uid =", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidNotEqualTo(String value) {
            addCriterion("salesman_uid <>", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidGreaterThan(String value) {
            addCriterion("salesman_uid >", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidGreaterThanOrEqualTo(String value) {
            addCriterion("salesman_uid >=", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidLessThan(String value) {
            addCriterion("salesman_uid <", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidLessThanOrEqualTo(String value) {
            addCriterion("salesman_uid <=", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidLike(String value) {
            addCriterion("salesman_uid like", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidNotLike(String value) {
            addCriterion("salesman_uid not like", value, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidIn(List<String> values) {
            addCriterion("salesman_uid in", values, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidNotIn(List<String> values) {
            addCriterion("salesman_uid not in", values, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidBetween(String value1, String value2) {
            addCriterion("salesman_uid between", value1, value2, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSalesmanUidNotBetween(String value1, String value2) {
            addCriterion("salesman_uid not between", value1, value2, "salesmanUid");
            return (Criteria) this;
        }

        public Criteria andSignTimeIsNull() {
            addCriterion("sign_time is null");
            return (Criteria) this;
        }

        public Criteria andSignTimeIsNotNull() {
            addCriterion("sign_time is not null");
            return (Criteria) this;
        }

        public Criteria andSignTimeEqualTo(Date value) {
            addCriterion("sign_time =", value, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeNotEqualTo(Date value) {
            addCriterion("sign_time <>", value, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeGreaterThan(Date value) {
            addCriterion("sign_time >", value, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sign_time >=", value, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeLessThan(Date value) {
            addCriterion("sign_time <", value, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeLessThanOrEqualTo(Date value) {
            addCriterion("sign_time <=", value, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeIn(List<Date> values) {
            addCriterion("sign_time in", values, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeNotIn(List<Date> values) {
            addCriterion("sign_time not in", values, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeBetween(Date value1, Date value2) {
            addCriterion("sign_time between", value1, value2, "signTime");
            return (Criteria) this;
        }

        public Criteria andSignTimeNotBetween(Date value1, Date value2) {
            addCriterion("sign_time not between", value1, value2, "signTime");
            return (Criteria) this;
        }

        public Criteria andBoPriceIsNull() {
            addCriterion("bo_price is null");
            return (Criteria) this;
        }

        public Criteria andBoPriceIsNotNull() {
            addCriterion("bo_price is not null");
            return (Criteria) this;
        }

        public Criteria andBoPriceEqualTo(BigDecimal value) {
            addCriterion("bo_price =", value, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceNotEqualTo(BigDecimal value) {
            addCriterion("bo_price <>", value, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceGreaterThan(BigDecimal value) {
            addCriterion("bo_price >", value, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bo_price >=", value, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceLessThan(BigDecimal value) {
            addCriterion("bo_price <", value, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bo_price <=", value, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceIn(List<BigDecimal> values) {
            addCriterion("bo_price in", values, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceNotIn(List<BigDecimal> values) {
            addCriterion("bo_price not in", values, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bo_price between", value1, value2, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bo_price not between", value1, value2, "boPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceIsNull() {
            addCriterion("bo_finish_price is null");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceIsNotNull() {
            addCriterion("bo_finish_price is not null");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceEqualTo(BigDecimal value) {
            addCriterion("bo_finish_price =", value, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceNotEqualTo(BigDecimal value) {
            addCriterion("bo_finish_price <>", value, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceGreaterThan(BigDecimal value) {
            addCriterion("bo_finish_price >", value, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bo_finish_price >=", value, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceLessThan(BigDecimal value) {
            addCriterion("bo_finish_price <", value, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bo_finish_price <=", value, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceIn(List<BigDecimal> values) {
            addCriterion("bo_finish_price in", values, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceNotIn(List<BigDecimal> values) {
            addCriterion("bo_finish_price not in", values, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bo_finish_price between", value1, value2, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoFinishPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bo_finish_price not between", value1, value2, "boFinishPrice");
            return (Criteria) this;
        }

        public Criteria andBoExpectIsNull() {
            addCriterion("bo_expect is null");
            return (Criteria) this;
        }

        public Criteria andBoExpectIsNotNull() {
            addCriterion("bo_expect is not null");
            return (Criteria) this;
        }

        public Criteria andBoExpectEqualTo(Integer value) {
            addCriterion("bo_expect =", value, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectNotEqualTo(Integer value) {
            addCriterion("bo_expect <>", value, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectGreaterThan(Integer value) {
            addCriterion("bo_expect >", value, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_expect >=", value, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectLessThan(Integer value) {
            addCriterion("bo_expect <", value, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectLessThanOrEqualTo(Integer value) {
            addCriterion("bo_expect <=", value, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectIn(List<Integer> values) {
            addCriterion("bo_expect in", values, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectNotIn(List<Integer> values) {
            addCriterion("bo_expect not in", values, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectBetween(Integer value1, Integer value2) {
            addCriterion("bo_expect between", value1, value2, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_expect not between", value1, value2, "boExpect");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitIsNull() {
            addCriterion("bo_expect_unit is null");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitIsNotNull() {
            addCriterion("bo_expect_unit is not null");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitEqualTo(Integer value) {
            addCriterion("bo_expect_unit =", value, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitNotEqualTo(Integer value) {
            addCriterion("bo_expect_unit <>", value, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitGreaterThan(Integer value) {
            addCriterion("bo_expect_unit >", value, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_expect_unit >=", value, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitLessThan(Integer value) {
            addCriterion("bo_expect_unit <", value, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitLessThanOrEqualTo(Integer value) {
            addCriterion("bo_expect_unit <=", value, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitIn(List<Integer> values) {
            addCriterion("bo_expect_unit in", values, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitNotIn(List<Integer> values) {
            addCriterion("bo_expect_unit not in", values, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitBetween(Integer value1, Integer value2) {
            addCriterion("bo_expect_unit between", value1, value2, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoExpectUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_expect_unit not between", value1, value2, "boExpectUnit");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeIsNull() {
            addCriterion("bo_paytype is null");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeIsNotNull() {
            addCriterion("bo_paytype is not null");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeEqualTo(Integer value) {
            addCriterion("bo_paytype =", value, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeNotEqualTo(Integer value) {
            addCriterion("bo_paytype <>", value, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeGreaterThan(Integer value) {
            addCriterion("bo_paytype >", value, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_paytype >=", value, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeLessThan(Integer value) {
            addCriterion("bo_paytype <", value, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeLessThanOrEqualTo(Integer value) {
            addCriterion("bo_paytype <=", value, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeIn(List<Integer> values) {
            addCriterion("bo_paytype in", values, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeNotIn(List<Integer> values) {
            addCriterion("bo_paytype not in", values, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeBetween(Integer value1, Integer value2) {
            addCriterion("bo_paytype between", value1, value2, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoPaytypeNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_paytype not between", value1, value2, "boPaytype");
            return (Criteria) this;
        }

        public Criteria andBoIsStateIsNull() {
            addCriterion("bo_is_state is null");
            return (Criteria) this;
        }

        public Criteria andBoIsStateIsNotNull() {
            addCriterion("bo_is_state is not null");
            return (Criteria) this;
        }

        public Criteria andBoIsStateEqualTo(Integer value) {
            addCriterion("bo_is_state =", value, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateNotEqualTo(Integer value) {
            addCriterion("bo_is_state <>", value, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateGreaterThan(Integer value) {
            addCriterion("bo_is_state >", value, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_is_state >=", value, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateLessThan(Integer value) {
            addCriterion("bo_is_state <", value, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateLessThanOrEqualTo(Integer value) {
            addCriterion("bo_is_state <=", value, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateIn(List<Integer> values) {
            addCriterion("bo_is_state in", values, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateNotIn(List<Integer> values) {
            addCriterion("bo_is_state not in", values, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateBetween(Integer value1, Integer value2) {
            addCriterion("bo_is_state between", value1, value2, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsStateNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_is_state not between", value1, value2, "boIsState");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishIsNull() {
            addCriterion("bo_is_finish is null");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishIsNotNull() {
            addCriterion("bo_is_finish is not null");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishEqualTo(Integer value) {
            addCriterion("bo_is_finish =", value, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishNotEqualTo(Integer value) {
            addCriterion("bo_is_finish <>", value, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishGreaterThan(Integer value) {
            addCriterion("bo_is_finish >", value, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_is_finish >=", value, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishLessThan(Integer value) {
            addCriterion("bo_is_finish <", value, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishLessThanOrEqualTo(Integer value) {
            addCriterion("bo_is_finish <=", value, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishIn(List<Integer> values) {
            addCriterion("bo_is_finish in", values, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishNotIn(List<Integer> values) {
            addCriterion("bo_is_finish not in", values, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishBetween(Integer value1, Integer value2) {
            addCriterion("bo_is_finish between", value1, value2, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoIsFinishNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_is_finish not between", value1, value2, "boIsFinish");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeIsNull() {
            addCriterion("bo_finish_time is null");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeIsNotNull() {
            addCriterion("bo_finish_time is not null");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeEqualTo(Date value) {
            addCriterion("bo_finish_time =", value, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeNotEqualTo(Date value) {
            addCriterion("bo_finish_time <>", value, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeGreaterThan(Date value) {
            addCriterion("bo_finish_time >", value, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("bo_finish_time >=", value, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeLessThan(Date value) {
            addCriterion("bo_finish_time <", value, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeLessThanOrEqualTo(Date value) {
            addCriterion("bo_finish_time <=", value, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeIn(List<Date> values) {
            addCriterion("bo_finish_time in", values, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeNotIn(List<Date> values) {
            addCriterion("bo_finish_time not in", values, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeBetween(Date value1, Date value2) {
            addCriterion("bo_finish_time between", value1, value2, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoFinishTimeNotBetween(Date value1, Date value2) {
            addCriterion("bo_finish_time not between", value1, value2, "boFinishTime");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceIsNull() {
            addCriterion("bo_pay_source is null");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceIsNotNull() {
            addCriterion("bo_pay_source is not null");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceEqualTo(String value) {
            addCriterion("bo_pay_source =", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceNotEqualTo(String value) {
            addCriterion("bo_pay_source <>", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceGreaterThan(String value) {
            addCriterion("bo_pay_source >", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceGreaterThanOrEqualTo(String value) {
            addCriterion("bo_pay_source >=", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceLessThan(String value) {
            addCriterion("bo_pay_source <", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceLessThanOrEqualTo(String value) {
            addCriterion("bo_pay_source <=", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceLike(String value) {
            addCriterion("bo_pay_source like", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceNotLike(String value) {
            addCriterion("bo_pay_source not like", value, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceIn(List<String> values) {
            addCriterion("bo_pay_source in", values, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceNotIn(List<String> values) {
            addCriterion("bo_pay_source not in", values, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceBetween(String value1, String value2) {
            addCriterion("bo_pay_source between", value1, value2, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPaySourceNotBetween(String value1, String value2) {
            addCriterion("bo_pay_source not between", value1, value2, "boPaySource");
            return (Criteria) this;
        }

        public Criteria andBoPayStateIsNull() {
            addCriterion("bo_pay_state is null");
            return (Criteria) this;
        }

        public Criteria andBoPayStateIsNotNull() {
            addCriterion("bo_pay_state is not null");
            return (Criteria) this;
        }

        public Criteria andBoPayStateEqualTo(Integer value) {
            addCriterion("bo_pay_state =", value, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateNotEqualTo(Integer value) {
            addCriterion("bo_pay_state <>", value, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateGreaterThan(Integer value) {
            addCriterion("bo_pay_state >", value, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_pay_state >=", value, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateLessThan(Integer value) {
            addCriterion("bo_pay_state <", value, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateLessThanOrEqualTo(Integer value) {
            addCriterion("bo_pay_state <=", value, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateIn(List<Integer> values) {
            addCriterion("bo_pay_state in", values, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateNotIn(List<Integer> values) {
            addCriterion("bo_pay_state not in", values, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateBetween(Integer value1, Integer value2) {
            addCriterion("bo_pay_state between", value1, value2, "boPayState");
            return (Criteria) this;
        }

        public Criteria andBoPayStateNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_pay_state not between", value1, value2, "boPayState");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeIsNull() {
            addCriterion("first_pay_time is null");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeIsNotNull() {
            addCriterion("first_pay_time is not null");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeEqualTo(Date value) {
            addCriterion("first_pay_time =", value, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeNotEqualTo(Date value) {
            addCriterion("first_pay_time <>", value, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeGreaterThan(Date value) {
            addCriterion("first_pay_time >", value, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("first_pay_time >=", value, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeLessThan(Date value) {
            addCriterion("first_pay_time <", value, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("first_pay_time <=", value, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeIn(List<Date> values) {
            addCriterion("first_pay_time in", values, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeNotIn(List<Date> values) {
            addCriterion("first_pay_time not in", values, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeBetween(Date value1, Date value2) {
            addCriterion("first_pay_time between", value1, value2, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andFirstPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("first_pay_time not between", value1, value2, "firstPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeIsNull() {
            addCriterion("last_pay_time is null");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeIsNotNull() {
            addCriterion("last_pay_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeEqualTo(Date value) {
            addCriterion("last_pay_time =", value, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeNotEqualTo(Date value) {
            addCriterion("last_pay_time <>", value, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeGreaterThan(Date value) {
            addCriterion("last_pay_time >", value, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_pay_time >=", value, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeLessThan(Date value) {
            addCriterion("last_pay_time <", value, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_pay_time <=", value, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeIn(List<Date> values) {
            addCriterion("last_pay_time in", values, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeNotIn(List<Date> values) {
            addCriterion("last_pay_time not in", values, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeBetween(Date value1, Date value2) {
            addCriterion("last_pay_time between", value1, value2, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andLastPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_pay_time not between", value1, value2, "lastPayTime");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectIsNull() {
            addCriterion("bo_pay_expect is null");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectIsNotNull() {
            addCriterion("bo_pay_expect is not null");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectEqualTo(Integer value) {
            addCriterion("bo_pay_expect =", value, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectNotEqualTo(Integer value) {
            addCriterion("bo_pay_expect <>", value, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectGreaterThan(Integer value) {
            addCriterion("bo_pay_expect >", value, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectGreaterThanOrEqualTo(Integer value) {
            addCriterion("bo_pay_expect >=", value, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectLessThan(Integer value) {
            addCriterion("bo_pay_expect <", value, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectLessThanOrEqualTo(Integer value) {
            addCriterion("bo_pay_expect <=", value, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectIn(List<Integer> values) {
            addCriterion("bo_pay_expect in", values, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectNotIn(List<Integer> values) {
            addCriterion("bo_pay_expect not in", values, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectBetween(Integer value1, Integer value2) {
            addCriterion("bo_pay_expect between", value1, value2, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andBoPayExpectNotBetween(Integer value1, Integer value2) {
            addCriterion("bo_pay_expect not between", value1, value2, "boPayExpect");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeIsNull() {
            addCriterion("first_expect_time is null");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeIsNotNull() {
            addCriterion("first_expect_time is not null");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeEqualTo(Date value) {
            addCriterion("first_expect_time =", value, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeNotEqualTo(Date value) {
            addCriterion("first_expect_time <>", value, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeGreaterThan(Date value) {
            addCriterion("first_expect_time >", value, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("first_expect_time >=", value, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeLessThan(Date value) {
            addCriterion("first_expect_time <", value, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeLessThanOrEqualTo(Date value) {
            addCriterion("first_expect_time <=", value, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeIn(List<Date> values) {
            addCriterion("first_expect_time in", values, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeNotIn(List<Date> values) {
            addCriterion("first_expect_time not in", values, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeBetween(Date value1, Date value2) {
            addCriterion("first_expect_time between", value1, value2, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andFirstExpectTimeNotBetween(Date value1, Date value2) {
            addCriterion("first_expect_time not between", value1, value2, "firstExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeIsNull() {
            addCriterion("last_expect_time is null");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeIsNotNull() {
            addCriterion("last_expect_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeEqualTo(Date value) {
            addCriterion("last_expect_time =", value, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeNotEqualTo(Date value) {
            addCriterion("last_expect_time <>", value, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeGreaterThan(Date value) {
            addCriterion("last_expect_time >", value, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_expect_time >=", value, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeLessThan(Date value) {
            addCriterion("last_expect_time <", value, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_expect_time <=", value, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeIn(List<Date> values) {
            addCriterion("last_expect_time in", values, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeNotIn(List<Date> values) {
            addCriterion("last_expect_time not in", values, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeBetween(Date value1, Date value2) {
            addCriterion("last_expect_time between", value1, value2, "lastExpectTime");
            return (Criteria) this;
        }

        public Criteria andLastExpectTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_expect_time not between", value1, value2, "lastExpectTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
