package com.borrow.manage.model.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BorrowProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public BorrowProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNull() {
            addCriterion("disabled is null");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNotNull() {
            addCriterion("disabled is not null");
            return (Criteria) this;
        }

        public Criteria andDisabledEqualTo(Boolean value) {
            addCriterion("disabled =", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotEqualTo(Boolean value) {
            addCriterion("disabled <>", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThan(Boolean value) {
            addCriterion("disabled >", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("disabled >=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThan(Boolean value) {
            addCriterion("disabled <", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThanOrEqualTo(Boolean value) {
            addCriterion("disabled <=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledIn(List<Boolean> values) {
            addCriterion("disabled in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotIn(List<Boolean> values) {
            addCriterion("disabled not in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledBetween(Boolean value1, Boolean value2) {
            addCriterion("disabled between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("disabled not between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andPNameIsNull() {
            addCriterion("p_name is null");
            return (Criteria) this;
        }

        public Criteria andPNameIsNotNull() {
            addCriterion("p_name is not null");
            return (Criteria) this;
        }

        public Criteria andPNameEqualTo(String value) {
            addCriterion("p_name =", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotEqualTo(String value) {
            addCriterion("p_name <>", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThan(String value) {
            addCriterion("p_name >", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThanOrEqualTo(String value) {
            addCriterion("p_name >=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThan(String value) {
            addCriterion("p_name <", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThanOrEqualTo(String value) {
            addCriterion("p_name <=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLike(String value) {
            addCriterion("p_name like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotLike(String value) {
            addCriterion("p_name not like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameIn(List<String> values) {
            addCriterion("p_name in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotIn(List<String> values) {
            addCriterion("p_name not in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameBetween(String value1, String value2) {
            addCriterion("p_name between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotBetween(String value1, String value2) {
            addCriterion("p_name not between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andBussTypeIsNull() {
            addCriterion("buss_type is null");
            return (Criteria) this;
        }

        public Criteria andBussTypeIsNotNull() {
            addCriterion("buss_type is not null");
            return (Criteria) this;
        }

        public Criteria andBussTypeEqualTo(Integer value) {
            addCriterion("buss_type =", value, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeNotEqualTo(Integer value) {
            addCriterion("buss_type <>", value, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeGreaterThan(Integer value) {
            addCriterion("buss_type >", value, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("buss_type >=", value, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeLessThan(Integer value) {
            addCriterion("buss_type <", value, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeLessThanOrEqualTo(Integer value) {
            addCriterion("buss_type <=", value, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeIn(List<Integer> values) {
            addCriterion("buss_type in", values, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeNotIn(List<Integer> values) {
            addCriterion("buss_type not in", values, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeBetween(Integer value1, Integer value2) {
            addCriterion("buss_type between", value1, value2, "bussType");
            return (Criteria) this;
        }

        public Criteria andBussTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("buss_type not between", value1, value2, "bussType");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNull() {
            addCriterion("p_type is null");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNotNull() {
            addCriterion("p_type is not null");
            return (Criteria) this;
        }

        public Criteria andPTypeEqualTo(Integer value) {
            addCriterion("p_type =", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotEqualTo(Integer value) {
            addCriterion("p_type <>", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThan(Integer value) {
            addCriterion("p_type >", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_type >=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThan(Integer value) {
            addCriterion("p_type <", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThanOrEqualTo(Integer value) {
            addCriterion("p_type <=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeIn(List<Integer> values) {
            addCriterion("p_type in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotIn(List<Integer> values) {
            addCriterion("p_type not in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeBetween(Integer value1, Integer value2) {
            addCriterion("p_type between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("p_type not between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNull() {
            addCriterion("p_code is null");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNotNull() {
            addCriterion("p_code is not null");
            return (Criteria) this;
        }

        public Criteria andPCodeEqualTo(String value) {
            addCriterion("p_code =", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotEqualTo(String value) {
            addCriterion("p_code <>", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThan(String value) {
            addCriterion("p_code >", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThanOrEqualTo(String value) {
            addCriterion("p_code >=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThan(String value) {
            addCriterion("p_code <", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThanOrEqualTo(String value) {
            addCriterion("p_code <=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLike(String value) {
            addCriterion("p_code like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotLike(String value) {
            addCriterion("p_code not like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeIn(List<String> values) {
            addCriterion("p_code in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotIn(List<String> values) {
            addCriterion("p_code not in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeBetween(String value1, String value2) {
            addCriterion("p_code between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotBetween(String value1, String value2) {
            addCriterion("p_code not between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andPExpectIsNull() {
            addCriterion("p_expect is null");
            return (Criteria) this;
        }

        public Criteria andPExpectIsNotNull() {
            addCriterion("p_expect is not null");
            return (Criteria) this;
        }

        public Criteria andPExpectEqualTo(Integer value) {
            addCriterion("p_expect =", value, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectNotEqualTo(Integer value) {
            addCriterion("p_expect <>", value, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectGreaterThan(Integer value) {
            addCriterion("p_expect >", value, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_expect >=", value, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectLessThan(Integer value) {
            addCriterion("p_expect <", value, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectLessThanOrEqualTo(Integer value) {
            addCriterion("p_expect <=", value, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectIn(List<Integer> values) {
            addCriterion("p_expect in", values, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectNotIn(List<Integer> values) {
            addCriterion("p_expect not in", values, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectBetween(Integer value1, Integer value2) {
            addCriterion("p_expect between", value1, value2, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectNotBetween(Integer value1, Integer value2) {
            addCriterion("p_expect not between", value1, value2, "pExpect");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitIsNull() {
            addCriterion("p_expect_unit is null");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitIsNotNull() {
            addCriterion("p_expect_unit is not null");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitEqualTo(Integer value) {
            addCriterion("p_expect_unit =", value, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitNotEqualTo(Integer value) {
            addCriterion("p_expect_unit <>", value, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitGreaterThan(Integer value) {
            addCriterion("p_expect_unit >", value, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_expect_unit >=", value, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitLessThan(Integer value) {
            addCriterion("p_expect_unit <", value, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitLessThanOrEqualTo(Integer value) {
            addCriterion("p_expect_unit <=", value, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitIn(List<Integer> values) {
            addCriterion("p_expect_unit in", values, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitNotIn(List<Integer> values) {
            addCriterion("p_expect_unit not in", values, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitBetween(Integer value1, Integer value2) {
            addCriterion("p_expect_unit between", value1, value2, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPExpectUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("p_expect_unit not between", value1, value2, "pExpectUnit");
            return (Criteria) this;
        }

        public Criteria andPPriceMinIsNull() {
            addCriterion("p_price_min is null");
            return (Criteria) this;
        }

        public Criteria andPPriceMinIsNotNull() {
            addCriterion("p_price_min is not null");
            return (Criteria) this;
        }

        public Criteria andPPriceMinEqualTo(BigDecimal value) {
            addCriterion("p_price_min =", value, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinNotEqualTo(BigDecimal value) {
            addCriterion("p_price_min <>", value, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinGreaterThan(BigDecimal value) {
            addCriterion("p_price_min >", value, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("p_price_min >=", value, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinLessThan(BigDecimal value) {
            addCriterion("p_price_min <", value, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("p_price_min <=", value, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinIn(List<BigDecimal> values) {
            addCriterion("p_price_min in", values, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinNotIn(List<BigDecimal> values) {
            addCriterion("p_price_min not in", values, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("p_price_min between", value1, value2, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("p_price_min not between", value1, value2, "pPriceMin");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxIsNull() {
            addCriterion("p_price_max is null");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxIsNotNull() {
            addCriterion("p_price_max is not null");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxEqualTo(BigDecimal value) {
            addCriterion("p_price_max =", value, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxNotEqualTo(BigDecimal value) {
            addCriterion("p_price_max <>", value, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxGreaterThan(BigDecimal value) {
            addCriterion("p_price_max >", value, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("p_price_max >=", value, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxLessThan(BigDecimal value) {
            addCriterion("p_price_max <", value, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("p_price_max <=", value, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxIn(List<BigDecimal> values) {
            addCriterion("p_price_max in", values, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxNotIn(List<BigDecimal> values) {
            addCriterion("p_price_max not in", values, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("p_price_max between", value1, value2, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPriceMaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("p_price_max not between", value1, value2, "pPriceMax");
            return (Criteria) this;
        }

        public Criteria andPPayTypeIsNull() {
            addCriterion("p_pay_type is null");
            return (Criteria) this;
        }

        public Criteria andPPayTypeIsNotNull() {
            addCriterion("p_pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPPayTypeEqualTo(Integer value) {
            addCriterion("p_pay_type =", value, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeNotEqualTo(Integer value) {
            addCriterion("p_pay_type <>", value, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeGreaterThan(Integer value) {
            addCriterion("p_pay_type >", value, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_pay_type >=", value, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeLessThan(Integer value) {
            addCriterion("p_pay_type <", value, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("p_pay_type <=", value, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeIn(List<Integer> values) {
            addCriterion("p_pay_type in", values, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeNotIn(List<Integer> values) {
            addCriterion("p_pay_type not in", values, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeBetween(Integer value1, Integer value2) {
            addCriterion("p_pay_type between", value1, value2, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPPayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("p_pay_type not between", value1, value2, "pPayType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeIsNull() {
            addCriterion("p_accept_type is null");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeIsNotNull() {
            addCriterion("p_accept_type is not null");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeEqualTo(Integer value) {
            addCriterion("p_accept_type =", value, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeNotEqualTo(Integer value) {
            addCriterion("p_accept_type <>", value, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeGreaterThan(Integer value) {
            addCriterion("p_accept_type >", value, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_accept_type >=", value, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeLessThan(Integer value) {
            addCriterion("p_accept_type <", value, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeLessThanOrEqualTo(Integer value) {
            addCriterion("p_accept_type <=", value, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeIn(List<Integer> values) {
            addCriterion("p_accept_type in", values, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeNotIn(List<Integer> values) {
            addCriterion("p_accept_type not in", values, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeBetween(Integer value1, Integer value2) {
            addCriterion("p_accept_type between", value1, value2, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPAcceptTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("p_accept_type not between", value1, value2, "pAcceptType");
            return (Criteria) this;
        }

        public Criteria andPEnabledIsNull() {
            addCriterion("p_enabled is null");
            return (Criteria) this;
        }

        public Criteria andPEnabledIsNotNull() {
            addCriterion("p_enabled is not null");
            return (Criteria) this;
        }

        public Criteria andPEnabledEqualTo(Integer value) {
            addCriterion("p_enabled =", value, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledNotEqualTo(Integer value) {
            addCriterion("p_enabled <>", value, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledGreaterThan(Integer value) {
            addCriterion("p_enabled >", value, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_enabled >=", value, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledLessThan(Integer value) {
            addCriterion("p_enabled <", value, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledLessThanOrEqualTo(Integer value) {
            addCriterion("p_enabled <=", value, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledIn(List<Integer> values) {
            addCriterion("p_enabled in", values, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledNotIn(List<Integer> values) {
            addCriterion("p_enabled not in", values, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledBetween(Integer value1, Integer value2) {
            addCriterion("p_enabled between", value1, value2, "pEnabled");
            return (Criteria) this;
        }

        public Criteria andPEnabledNotBetween(Integer value1, Integer value2) {
            addCriterion("p_enabled not between", value1, value2, "pEnabled");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}