package com.borrow.manage.model.dto;

import java.math.BigDecimal;
import java.util.Date;

public class BorrowRepayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.repay_id
     *
     * @mbggenerated
     */
    private Long repayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.user_uid
     *
     * @mbggenerated
     */
    private String userUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.repay_amount
     *
     * @mbggenerated
     */
    private BigDecimal repayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.capital_amount
     *
     * @mbggenerated
     */
    private BigDecimal capitalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.br_time
     *
     * @mbggenerated
     */
    private Date brTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.br_repay_time
     *
     * @mbggenerated
     */
    private Date brRepayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.repay_expect
     *
     * @mbggenerated
     */
    private Integer repayExpect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.interest_amount
     *
     * @mbggenerated
     */
    private BigDecimal interestAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.punish_amount
     *
     * @mbggenerated
     */
    private BigDecimal punishAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.service_fee
     *
     * @mbggenerated
     */
    private BigDecimal serviceFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.early_pay_fee
     *
     * @mbggenerated
     */
    private BigDecimal earlyPayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.repay_status
     *
     * @mbggenerated
     */
    private Integer repayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.bo_repay_status
     *
     * @mbggenerated
     */
    private Integer boRepayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.repay_type
     *
     * @mbggenerated
     */
    private Integer repayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.repay_finish_amount
     *
     * @mbggenerated
     */
    private BigDecimal repayFinishAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.surety_status
     *
     * @mbggenerated
     */
    private Integer suretyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.surety_time
     *
     * @mbggenerated
     */
    private Date suretyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_repayment.fine_amount
     *
     * @mbggenerated
     */
    private BigDecimal fineAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.id
     *
     * @return the value of borrow_repayment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.id
     *
     * @param id the value for borrow_repayment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.disabled
     *
     * @return the value of borrow_repayment.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.disabled
     *
     * @param disabled the value for borrow_repayment.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.uuid
     *
     * @return the value of borrow_repayment.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.uuid
     *
     * @param uuid the value for borrow_repayment.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.create_user
     *
     * @return the value of borrow_repayment.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.create_user
     *
     * @param createUser the value for borrow_repayment.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.create_time
     *
     * @return the value of borrow_repayment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.create_time
     *
     * @param createTime the value for borrow_repayment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.update_user
     *
     * @return the value of borrow_repayment.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.update_user
     *
     * @param updateUser the value for borrow_repayment.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.update_time
     *
     * @return the value of borrow_repayment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.update_time
     *
     * @param updateTime the value for borrow_repayment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.remark
     *
     * @return the value of borrow_repayment.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.remark
     *
     * @param remark the value for borrow_repayment.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.repay_id
     *
     * @return the value of borrow_repayment.repay_id
     *
     * @mbggenerated
     */
    public Long getRepayId() {
        return repayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.repay_id
     *
     * @param repayId the value for borrow_repayment.repay_id
     *
     * @mbggenerated
     */
    public void setRepayId(Long repayId) {
        this.repayId = repayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.order_id
     *
     * @return the value of borrow_repayment.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.order_id
     *
     * @param orderId the value for borrow_repayment.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.user_uid
     *
     * @return the value of borrow_repayment.user_uid
     *
     * @mbggenerated
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.user_uid
     *
     * @param userUid the value for borrow_repayment.user_uid
     *
     * @mbggenerated
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.repay_amount
     *
     * @return the value of borrow_repayment.repay_amount
     *
     * @mbggenerated
     */
    public BigDecimal getRepayAmount() {
        return repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.repay_amount
     *
     * @param repayAmount the value for borrow_repayment.repay_amount
     *
     * @mbggenerated
     */
    public void setRepayAmount(BigDecimal repayAmount) {
        this.repayAmount = repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.capital_amount
     *
     * @return the value of borrow_repayment.capital_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCapitalAmount() {
        return capitalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.capital_amount
     *
     * @param capitalAmount the value for borrow_repayment.capital_amount
     *
     * @mbggenerated
     */
    public void setCapitalAmount(BigDecimal capitalAmount) {
        this.capitalAmount = capitalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.br_time
     *
     * @return the value of borrow_repayment.br_time
     *
     * @mbggenerated
     */
    public Date getBrTime() {
        return brTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.br_time
     *
     * @param brTime the value for borrow_repayment.br_time
     *
     * @mbggenerated
     */
    public void setBrTime(Date brTime) {
        this.brTime = brTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.br_repay_time
     *
     * @return the value of borrow_repayment.br_repay_time
     *
     * @mbggenerated
     */
    public Date getBrRepayTime() {
        return brRepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.br_repay_time
     *
     * @param brRepayTime the value for borrow_repayment.br_repay_time
     *
     * @mbggenerated
     */
    public void setBrRepayTime(Date brRepayTime) {
        this.brRepayTime = brRepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.repay_expect
     *
     * @return the value of borrow_repayment.repay_expect
     *
     * @mbggenerated
     */
    public Integer getRepayExpect() {
        return repayExpect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.repay_expect
     *
     * @param repayExpect the value for borrow_repayment.repay_expect
     *
     * @mbggenerated
     */
    public void setRepayExpect(Integer repayExpect) {
        this.repayExpect = repayExpect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.interest_amount
     *
     * @return the value of borrow_repayment.interest_amount
     *
     * @mbggenerated
     */
    public BigDecimal getInterestAmount() {
        return interestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.interest_amount
     *
     * @param interestAmount the value for borrow_repayment.interest_amount
     *
     * @mbggenerated
     */
    public void setInterestAmount(BigDecimal interestAmount) {
        this.interestAmount = interestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.punish_amount
     *
     * @return the value of borrow_repayment.punish_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPunishAmount() {
        return punishAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.punish_amount
     *
     * @param punishAmount the value for borrow_repayment.punish_amount
     *
     * @mbggenerated
     */
    public void setPunishAmount(BigDecimal punishAmount) {
        this.punishAmount = punishAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.service_fee
     *
     * @return the value of borrow_repayment.service_fee
     *
     * @mbggenerated
     */
    public BigDecimal getServiceFee() {
        return serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.service_fee
     *
     * @param serviceFee the value for borrow_repayment.service_fee
     *
     * @mbggenerated
     */
    public void setServiceFee(BigDecimal serviceFee) {
        this.serviceFee = serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.early_pay_fee
     *
     * @return the value of borrow_repayment.early_pay_fee
     *
     * @mbggenerated
     */
    public BigDecimal getEarlyPayFee() {
        return earlyPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.early_pay_fee
     *
     * @param earlyPayFee the value for borrow_repayment.early_pay_fee
     *
     * @mbggenerated
     */
    public void setEarlyPayFee(BigDecimal earlyPayFee) {
        this.earlyPayFee = earlyPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.repay_status
     *
     * @return the value of borrow_repayment.repay_status
     *
     * @mbggenerated
     */
    public Integer getRepayStatus() {
        return repayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.repay_status
     *
     * @param repayStatus the value for borrow_repayment.repay_status
     *
     * @mbggenerated
     */
    public void setRepayStatus(Integer repayStatus) {
        this.repayStatus = repayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.bo_repay_status
     *
     * @return the value of borrow_repayment.bo_repay_status
     *
     * @mbggenerated
     */
    public Integer getBoRepayStatus() {
        return boRepayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.bo_repay_status
     *
     * @param boRepayStatus the value for borrow_repayment.bo_repay_status
     *
     * @mbggenerated
     */
    public void setBoRepayStatus(Integer boRepayStatus) {
        this.boRepayStatus = boRepayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.repay_type
     *
     * @return the value of borrow_repayment.repay_type
     *
     * @mbggenerated
     */
    public Integer getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.repay_type
     *
     * @param repayType the value for borrow_repayment.repay_type
     *
     * @mbggenerated
     */
    public void setRepayType(Integer repayType) {
        this.repayType = repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.repay_finish_amount
     *
     * @return the value of borrow_repayment.repay_finish_amount
     *
     * @mbggenerated
     */
    public BigDecimal getRepayFinishAmount() {
        return repayFinishAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.repay_finish_amount
     *
     * @param repayFinishAmount the value for borrow_repayment.repay_finish_amount
     *
     * @mbggenerated
     */
    public void setRepayFinishAmount(BigDecimal repayFinishAmount) {
        this.repayFinishAmount = repayFinishAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.surety_status
     *
     * @return the value of borrow_repayment.surety_status
     *
     * @mbggenerated
     */
    public Integer getSuretyStatus() {
        return suretyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.surety_status
     *
     * @param suretyStatus the value for borrow_repayment.surety_status
     *
     * @mbggenerated
     */
    public void setSuretyStatus(Integer suretyStatus) {
        this.suretyStatus = suretyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.surety_time
     *
     * @return the value of borrow_repayment.surety_time
     *
     * @mbggenerated
     */
    public Date getSuretyTime() {
        return suretyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.surety_time
     *
     * @param suretyTime the value for borrow_repayment.surety_time
     *
     * @mbggenerated
     */
    public void setSuretyTime(Date suretyTime) {
        this.suretyTime = suretyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_repayment.fine_amount
     *
     * @return the value of borrow_repayment.fine_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFineAmount() {
        return fineAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_repayment.fine_amount
     *
     * @param fineAmount the value for borrow_repayment.fine_amount
     *
     * @mbggenerated
     */
    public void setFineAmount(BigDecimal fineAmount) {
        this.fineAmount = fineAmount;
    }
}