package com.borrow.manage.model.dto;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.credit_status
     *
     * @mbggenerated
     */
    private Integer creditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.credit_dec
     *
     * @mbggenerated
     */
    private String creditDec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.work_nature
     *
     * @mbggenerated
     */
    private String workNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_earns
     *
     * @mbggenerated
     */
    private String userEarns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.marriage_status
     *
     * @mbggenerated
     */
    private Integer marriageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.children_desc
     *
     * @mbggenerated
     */
    private String childrenDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.liabilities_desc
     *
     * @mbggenerated
     */
    private String liabilitiesDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.guarantee_desc
     *
     * @mbggenerated
     */
    private String guaranteeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.disabled
     *
     * @return the value of user_info.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.disabled
     *
     * @param disabled the value for user_info.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uuid
     *
     * @return the value of user_info.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uuid
     *
     * @param uuid the value for user_info.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_user
     *
     * @return the value of user_info.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_user
     *
     * @param createUser the value for user_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_user
     *
     * @return the value of user_info.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_user
     *
     * @param updateUser the value for user_info.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.remark
     *
     * @return the value of user_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.remark
     *
     * @param remark the value for user_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.idcard
     *
     * @return the value of user_info.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.idcard
     *
     * @param idcard the value for user_info.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.credit_status
     *
     * @return the value of user_info.credit_status
     *
     * @mbggenerated
     */
    public Integer getCreditStatus() {
        return creditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.credit_status
     *
     * @param creditStatus the value for user_info.credit_status
     *
     * @mbggenerated
     */
    public void setCreditStatus(Integer creditStatus) {
        this.creditStatus = creditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.credit_dec
     *
     * @return the value of user_info.credit_dec
     *
     * @mbggenerated
     */
    public String getCreditDec() {
        return creditDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.credit_dec
     *
     * @param creditDec the value for user_info.credit_dec
     *
     * @mbggenerated
     */
    public void setCreditDec(String creditDec) {
        this.creditDec = creditDec == null ? null : creditDec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.industry
     *
     * @return the value of user_info.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.industry
     *
     * @param industry the value for user_info.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.work_nature
     *
     * @return the value of user_info.work_nature
     *
     * @mbggenerated
     */
    public String getWorkNature() {
        return workNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.work_nature
     *
     * @param workNature the value for user_info.work_nature
     *
     * @mbggenerated
     */
    public void setWorkNature(String workNature) {
        this.workNature = workNature == null ? null : workNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_earns
     *
     * @return the value of user_info.user_earns
     *
     * @mbggenerated
     */
    public String getUserEarns() {
        return userEarns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_earns
     *
     * @param userEarns the value for user_info.user_earns
     *
     * @mbggenerated
     */
    public void setUserEarns(String userEarns) {
        this.userEarns = userEarns == null ? null : userEarns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.marriage_status
     *
     * @return the value of user_info.marriage_status
     *
     * @mbggenerated
     */
    public Integer getMarriageStatus() {
        return marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.marriage_status
     *
     * @param marriageStatus the value for user_info.marriage_status
     *
     * @mbggenerated
     */
    public void setMarriageStatus(Integer marriageStatus) {
        this.marriageStatus = marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.children_desc
     *
     * @return the value of user_info.children_desc
     *
     * @mbggenerated
     */
    public String getChildrenDesc() {
        return childrenDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.children_desc
     *
     * @param childrenDesc the value for user_info.children_desc
     *
     * @mbggenerated
     */
    public void setChildrenDesc(String childrenDesc) {
        this.childrenDesc = childrenDesc == null ? null : childrenDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.liabilities_desc
     *
     * @return the value of user_info.liabilities_desc
     *
     * @mbggenerated
     */
    public String getLiabilitiesDesc() {
        return liabilitiesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.liabilities_desc
     *
     * @param liabilitiesDesc the value for user_info.liabilities_desc
     *
     * @mbggenerated
     */
    public void setLiabilitiesDesc(String liabilitiesDesc) {
        this.liabilitiesDesc = liabilitiesDesc == null ? null : liabilitiesDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.guarantee_desc
     *
     * @return the value of user_info.guarantee_desc
     *
     * @mbggenerated
     */
    public String getGuaranteeDesc() {
        return guaranteeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.guarantee_desc
     *
     * @param guaranteeDesc the value for user_info.guarantee_desc
     *
     * @mbggenerated
     */
    public void setGuaranteeDesc(String guaranteeDesc) {
        this.guaranteeDesc = guaranteeDesc == null ? null : guaranteeDesc.trim();
    }
}
