package com.borrow.manage.model.dto;

import java.math.BigDecimal;
import java.util.Date;

public class UserCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.car_name
     *
     * @mbggenerated
     */
    private String carName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.plate_number
     *
     * @mbggenerated
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.user_uid
     *
     * @mbggenerated
     */
    private String userUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.car_model
     *
     * @mbggenerated
     */
    private String carModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.car_color
     *
     * @mbggenerated
     */
    private String carColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.sign_time
     *
     * @mbggenerated
     */
    private Date signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.assessment_price
     *
     * @mbggenerated
     */
    private BigDecimal assessmentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_car.mileage_desc
     *
     * @mbggenerated
     */
    private String mileageDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.id
     *
     * @return the value of user_car.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.id
     *
     * @param id the value for user_car.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.disabled
     *
     * @return the value of user_car.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.disabled
     *
     * @param disabled the value for user_car.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.uuid
     *
     * @return the value of user_car.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.uuid
     *
     * @param uuid the value for user_car.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.create_user
     *
     * @return the value of user_car.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.create_user
     *
     * @param createUser the value for user_car.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.create_time
     *
     * @return the value of user_car.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.create_time
     *
     * @param createTime the value for user_car.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.update_user
     *
     * @return the value of user_car.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.update_user
     *
     * @param updateUser the value for user_car.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.update_time
     *
     * @return the value of user_car.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.update_time
     *
     * @param updateTime the value for user_car.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.remark
     *
     * @return the value of user_car.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.remark
     *
     * @param remark the value for user_car.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.car_name
     *
     * @return the value of user_car.car_name
     *
     * @mbggenerated
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.car_name
     *
     * @param carName the value for user_car.car_name
     *
     * @mbggenerated
     */
    public void setCarName(String carName) {
        this.carName = carName == null ? null : carName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.plate_number
     *
     * @return the value of user_car.plate_number
     *
     * @mbggenerated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.plate_number
     *
     * @param plateNumber the value for user_car.plate_number
     *
     * @mbggenerated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.user_uid
     *
     * @return the value of user_car.user_uid
     *
     * @mbggenerated
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.user_uid
     *
     * @param userUid the value for user_car.user_uid
     *
     * @mbggenerated
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.car_model
     *
     * @return the value of user_car.car_model
     *
     * @mbggenerated
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.car_model
     *
     * @param carModel the value for user_car.car_model
     *
     * @mbggenerated
     */
    public void setCarModel(String carModel) {
        this.carModel = carModel == null ? null : carModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.car_color
     *
     * @return the value of user_car.car_color
     *
     * @mbggenerated
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.car_color
     *
     * @param carColor the value for user_car.car_color
     *
     * @mbggenerated
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor == null ? null : carColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.sign_time
     *
     * @return the value of user_car.sign_time
     *
     * @mbggenerated
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.sign_time
     *
     * @param signTime the value for user_car.sign_time
     *
     * @mbggenerated
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.assessment_price
     *
     * @return the value of user_car.assessment_price
     *
     * @mbggenerated
     */
    public BigDecimal getAssessmentPrice() {
        return assessmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.assessment_price
     *
     * @param assessmentPrice the value for user_car.assessment_price
     *
     * @mbggenerated
     */
    public void setAssessmentPrice(BigDecimal assessmentPrice) {
        this.assessmentPrice = assessmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_car.mileage_desc
     *
     * @return the value of user_car.mileage_desc
     *
     * @mbggenerated
     */
    public String getMileageDesc() {
        return mileageDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_car.mileage_desc
     *
     * @param mileageDesc the value for user_car.mileage_desc
     *
     * @mbggenerated
     */
    public void setMileageDesc(String mileageDesc) {
        this.mileageDesc = mileageDesc == null ? null : mileageDesc.trim();
    }
}
